apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media-pvc
  labels:
    name: netbox-media-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  ##storageClassName: rook-cephfs #changeme
