apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media-pvc
  labels:
    name: netbox-media-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path #removing doesn't use default for some reason?
