apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media-pvc
  labels:
    name: netbox-media-pvc
spec:
  ### accessModes:
  ### - ReadWriteMany #put back when we move to ceph storage
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path #removing doesn't use default for some reason?
